### ISSUE TITLE
Please help with source without VGA and Wifi

### ISSUE THREAD

**Issue by vuminhthanh3010** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#10]
Hello
I am using Main like you, but I don't have VGA and Wifi. Can you give me the source after deleting the repair part of the VGA and Wifi? Thanks you very much. Hope you help me

**Comment by VanXNF** [comment]
> Hello
> I am using Main like you, but I don't have VGA and Wifi. Can you give me the source after deleting the repair part of the VGA and Wifi? Thanks you very much. Hope you help me

first Read my readme
and then just remove AirportItlwm.kext, IntelBluetoothFirmware.kext, IntelBluetoothInjector.kext, RadeonBoost.kext.
and try my new upload EFI.

**Comment by vuminhthanh3010** [comment]
In the config.plist file, do I have to remove the unused content?

**Comment by VanXNF** [comment]
sure, just use ProperTree to reload.
