### ISSUE TITLE
Some help here please

### ISSUE THREAD

**Issue by MeherBa** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#14]
Hello, i have the same motherboard (Bios: F5b)  and had issues to install Big sur
Errors : 
![teued61vkng61](https://user-images.githubusercontent.com/47627084/107643802-e93d9500-6c76-11eb-9144-c4b1a87a8f83.jpg)
![chdey01vkng61](https://user-images.githubusercontent.com/47627084/107643823-ee9adf80-6c76-11eb-9a00-13acf4499ba9.jpg)

And my [EFI folder](https://drive.google.com/file/d/1rpimaQ-6HjL21lmGi4ewjdqizXq_TXNP/view?usp=sharing)

Specs :

CPU : i5-10400 with intel UHD 630

GPU : GTX 650 (will be disabled with SSDT)

Motherboard : Gigabyte b460m aorus pro (Bios: F5b)

SSD : TeamGroup (Windows already installed)

**Comment by VanXNF** [comment]
sorry, I think I can do nothing about this. Try seeking some help on the forum.
