### ISSUE TITLE
Mic too low and Problem when use multi displays

### ISSUE THREAD

**Issue by memsenpai** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#18]
- My mic volume is too low, even when I shouted into the microphone, it was still small.
- I using two display: DP for 4k and hdmi for 2k. Screen will be black/ flicking when startup. I must restart screen 4k for work.
- 
![image](https://user-images.githubusercontent.com/10399540/115950117-951b2080-a503-11eb-8aa8-d8adedc6df00.png)
![image](https://user-images.githubusercontent.com/10399540/115950125-9c422e80-a503-11eb-8d48-50e1e1162db1.png)

**Comment by VanXNF** [comment]
The mic works well on my PC, so it will not be modified.
And you can try my new build for multi displays.

**Comment by memsenpai** [comment]
@VanXNF 
> The mic works well on my PC, so it will not be modified.
Which port do you use?
this is mine
I used the front mic port (on the case, other ports not work)
layout-id 50

actually, the volume is too low, and it will be lost some words when you start talking, look like macOS have some feature like "reduce noise"
example: I said: "Hello, yesterday, I did.."
the machine will receive from "I did..."

**Comment by VanXNF** [comment]
> 

This problem has not appeared here for me, and I have been busy with work recently, so please try to solve it yourself.

**Comment by VanXNF** [comment]
> @VanXNF
> 
> > The mic works well on my PC, so it will not be modified.
> > Which port do you use?
> > this is mine
> > I used the front mic port (on the case, other ports not work)
> > layout-id 50
> 
> actually, the volume is too low, and it will be lost some words when you start talking, look like macOS have some feature like "reduce noise" example: I said: "Hello, yesterday, I did.." the machine will receive from "I did..."

This problem has not appeared here for me, and I have been busy with work recently, so please try to solve it yourself.
