### ISSUE TITLE
ACPI 里面没用 SSDT-USBX ，是B460主板都不用修正 USB 电源这个问题了吗？

### ISSUE THREAD

**Issue by gzbenson** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#19]
B460 主板不需要 USBX 这个 SSDT 了吗？ 还是因为技嘉主板BIOS里面有一些设定，所以不需要
我用的是昂达的 B460 SD4 ITX 主板，我看主板BIOS有USB端口的屏蔽功能，如果直接在主板屏蔽的话，可以就不需要在config.list USB定制修正了

另外我安装好， Catalina 10.15.7 ，我的USB也是驱动不正常，只有主板IO面板里面两个后置USB2.0能用 ，其他的后置3.0和机箱前置的USB3.0都不能用（前置的USB3.0是机箱前置USB口（2个口，1根连接线）数据线直接插主板的USB端口）

**Comment by VanXNF** [comment]
> B460 主板不需要 USBX 这个 SSDT 了吗？ 还是因为技嘉主板BIOS里面有一些设定，所以不需要
> 我用的是昂达的 B460 SD4 ITX 主板，我看主板BIOS有USB端口的屏蔽功能，如果直接在主板屏蔽的话，可以就不需要在config.list USB定制修正了
> 
> 另外我安装好， Catalina 10.15.7 ，我的USB也是驱动不正常，只有主板IO面板里面两个后置USB2.0能用 ，其他的后置3.0和机箱前置的USB3.0都不能用（前置的USB3.0是机箱前置USB口（2个口，1根连接线）数据线直接插主板的USB端口）

USBX 只是开启 USB 额外电流，本质上还是需要主板的 USB 端口支持大电流输出才行，否则只是个显示（或是有可能减少 USB 端口寿命？），此外我也不需要 USB 给手机等设备供电，所以我就不做这个操作了。USB 端口本身是跟着主板走的，你用主板进行屏蔽的话就需要删除我的端口定制文件，否则也不会正常工作，当然最好的选择还是按自己的设备重新定制 USB。
