### ISSUE TITLE
睡眠问题

### ISSUE THREAD

**Issue by Versuspeople** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#22]
我想问下，这个只有集显的情况下用HDMI口连接显示器，睡眠正常吗

**Comment by VanXNF** [comment]
你自己试一下吧，我日常用都是用的独显上的dp。

Versuspeople ***@***.***> 于 2022年1月4日周二 22:58写道：

**Comment by Versuspeople** [comment]
好的，回去尝试一下，谢谢了

**Comment by Versuspeople** [comment]
对了，你用独显dp接口情况下睡眠没有问题吧

**Comment by VanXNF** [comment]
正常的

Versuspeople ***@***.***> 于 2022年1月6日周四 08:17写道：
