### ISSUE TITLE
Can I use without Graphic Card

### ISSUE THREAD

**Issue by anhnvme** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#23]
Hello,

Can i use this EFI without  Graphic card ?. 
I'm only have CPI i5-10400. i don't have amd or nvdia card

Thanks you

**Comment by VanXNF** [comment]
yes you can.
dp or hdmi of igpu will work.


anhnvme ***@***.***> 于 2022年1月12日周三 16:16写道：

**Comment by anhnvme** [comment]
Thank you !
