### ISSUE TITLE
AX200蓝牙不工作

### ISSUE THREAD

**Issue by meaverick** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#25]
从10开始，用着一直升级没问题，到montenery，AX200蓝牙不工作，配置几乎一样，显卡用核显，主板也一样，我比较了一个PLIST，都一样，改了个机器号和序列号UUID就完了，找不到原因。对了我多了个82599万兆网卡，它是自带安装驱动的，就当不影响。

**Comment by VanXNF** [comment]
我有段时间遇到过这个问题，在我这边是bios开启vt-d导致的，关闭后清除nvram解决，你可以检查一下bios，希望有所帮助

Neo ***@***.***> 于 2022年6月16日周四 11:00写道：

**Comment by meaverick** [comment]
VT-D我这边一直是关的，清了NVRAM，无效。等将来吧，说不定有解决方案，谢谢了！
