### ISSUE TITLE
usb C

### ISSUE THREAD

**Issue by memsenpai** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#26]
Can you fix it?
I used your efi
everything works well but USB C not work

**Comment by VanXNF** [comment]
> Can you fix it? I used your efi everything works well but USB C not work

maybe you can build your own USB layout by [USBToolBox](https://github.com/USBToolBox/tool).
because it depands on Mabo and Case front panel.

**Comment by memsenpai** [comment]
@VanXNF ah no, I mean the usb-c port on the mainboard
![Uploading Screen Shot 2022-09-27 at 17.21.43.png…]()

**Comment by VanXNF** [comment]
> @VanXNF ah no, I mean the usb-c port on the mainboard ![Screen Shot 2022-09-27 at 17 21 43](https://user-images.githubusercontent.com/10399540/192501270-5c7424da-24dc-4f4c-a7d7-96c1575ac2f5.png)

due to 15 ports limit, this type-c port only support USB3.0+ in my config, and it works well for my USB3.0 disk.
Please check if your type-c device only supports USB2.

**Comment by memsenpai** [comment]
thank you, I solved this issue by remapping usb ports with [USBToolBox](https://github.com/USBToolBox/tool).
