### ISSUE TITLE
问下配置

### ISSUE THREAD

**Issue by WEYAI** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#28]
您好，我的配置主板是技嘉B560M AORUS PRO AX主板，然后就是我的cpu是 i3-10100 也是十代的，这个会影响吗？内存条还有固态硬盘以及机械硬盘这些不会有影响吧，谢谢您能有时间回答下

**Comment by VanXNF** [comment]
> 您好，我的配置主板是技嘉B560M AORUS PRO AX主板，然后就是我的cpu是 i3-10100 也是十代的，这个会影响吗？内存条还有固态硬盘以及机械硬盘这些不会有影响吧，谢谢您能有时间回答下

B560M 不清楚会不会需要额外设置，内存条、固态（少数几个型号不行，可以网上查一下）和机械硬盘一般不会有影响。
