### ISSUE TITLE
Wi-Fi 6 AX200

### ISSUE THREAD

**Issue by yuanqingapp** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#29]
照你的配置买了主板和U, Wi-Fi 6 AX200能推个商家链接吗？有一个黑苹果BCM943602CS总是断连

**Comment by VanXNF** [comment]
> 照你的配置买了主板和U, Wi-Fi 6 AX200能推个商家链接吗？有一个黑苹果BCM943602CS总是断连

淘宝上直接买就可以，没什么区别的

**Comment by zyq2012** [comment]
- 无线网卡ax200ngw买好了，是直接用M2还是用转换到PCI插槽?
- 显示卡我加了个迪兰5500xt没声音，AMD Radeon RX 460 4G是什么品牌呢？
- 每次正常关机后，第二天开机会弹框显示异常关机。

**Comment by VanXNF** [comment]
> * 无线网卡ax200ngw买好了，是直接用M2还是用转换到PCI插槽?
> * 显示卡我加了个迪兰5500xt没声音，AMD Radeon RX 460 4G是什么品牌呢？
> * 每次正常关机后，第二天开机会弹框显示异常关机。

1. 用M2插槽就可以。
2. 5500XT 需要额外改一下[boot-args](https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#nvram:~:text=GPU%2DSpecific%20boot%2Dargs%3A)，具体看链接，不过没声音也不清楚是什么问题，应该是免驱的卡，不会有这样的问题，460也是迪兰的。
3. 这种情况清空一下NVRAM试试，以及用Hackintool修复一下电源或定制一下USB（如果机箱不一样，前置接口也不一样）试试，具体步骤可以直接按关键字搜索。
