### ISSUE TITLE
新手想问一些问题

### ISSUE THREAD

**Issue by ShiharaX** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#3]
AX200驱动在哪下载啊  我的显卡是 rx570 需要做改动吗

**Comment by VanXNF** [comment]
抱歉回复迟了，AX200 驱动在这个仓库 [itlwm](https://github.com/OpenIntelWireless/itlwm)。RX570的话应该是免驱的，不需要做改动。
