### ISSUE TITLE
最新版本无法点亮  11月8日的可以

### ISSUE THREAD

**Issue by huangfe1** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#30]

**Comment by huangfe1** [comment]
11月8日的EFI 开机比较慢 2-3分钟黑屏 才会亮

**Comment by VanXNF** [comment]
> 11月8日的EFI 开机比较慢 2-3分钟黑屏 才会亮

你的硬件配置是什么，最新版本取消了核显输出。

**Comment by huangfe1** [comment]
没想到作者能回复 首先感谢您分享 其次我已经用上了您最新的EFI 并且重装了系统回复您 之前的问题是我是6600xt显卡。这个系列的显卡 要加上防止黑屏参数。我加上了。 目前开机很快。 之前的莫名其妙会自动重启。  新版本目前暂未发现异常。 最后。再次感谢您的分享！持续关注作者！

**Comment by VanXNF** [comment]
> 没想到作者能回复 首先感谢您分享 其次我已经用上了您最新的EFI 并且重装了系统回复您 之前的问题是我是6600xt显卡。这个系列的显卡 要加上防止黑屏参数。我加上了。 目前开机很快。 之前的莫名其妙会自动重启。 新版本目前暂未发现异常。 最后。再次感谢您的分享！持续关注作者！

最近我也购买了6600XT，下一版本更新时会带上防黑参数。
