### ISSUE TITLE
显卡什么牌子版本呢？AMD Radeon RX 6600XT 8G

### ISSUE THREAD

**Issue by zyq2012** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#31]
感谢分享！如题，买的哪一款，信号线用的DP还是HDMI？

**Comment by VanXNF** [comment]
> 感谢分享！如题，买的哪一款，信号线用的DP还是HDMI？

我的是技嘉魔鹰Pro，日常用DP

**Comment by zyq2012** [comment]
现在6600没货没价格，技嘉魔鹰Pro只有6650，直接使用有区别么？

**Comment by VanXNF** [comment]
> 现在6600没货没价格，技嘉魔鹰Pro只有6650，直接使用有区别么？

6650XT不清楚是否免驱，免驱的话没差别的，只需要移除 [deviceproperties](https://github.com/VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#deviceproperties-%E9%83%A8%E5%88%86) 下的相关设置就行，不免驱的话可能要涉及到显卡仿冒，就需要你自己想办法了
