### ISSUE TITLE
关于USB定制方案

### ISSUE THREAD

**Issue by Cyanrel** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#32]
老哥我自用的也是b460m aorus pro+10400+5500xt，您的oc配置非常的完善出色，但同时我也有几个疑问，是关于USB定制项目的，您现成的方案是在ACPI中加入SSDT-EC.aml和SSDT-USBX.aml解决ec和供电问题，以及在kernel中使用USBToolBox.kext和UTBMap.kext来定制接口。
据我从各种论坛参考得知以及自己实验，这张型号的主板已经默认屏蔽了EC所以不需要SSDT-EC.aml，并且在Hackintosh下定制的USBPorts.kext可包含定制接口信息，即这一个就可以代替另外两个，而供电信息可以用USBPower.kext可解决，这样相对来说更加简洁高效。
关于为什么不修改ACPI而使用Kernel，因为10.15往后，usb的电源控制就直接放在了io resource，而在10.14中，苹果的usb电源控制是放在ec目录下的，所以写了ec都会写个usbx来帮助苹果具有电池的设备进行快速充电

**Comment by VanXNF** [comment]
> 老哥我自用的也是b460m aorus pro+10400+5500xt，您的oc配置非常的完善出色，但同时我也有几个疑问，是关于USB定制项目的，您现成的方案是在ACPI中加入SSDT-EC.aml和SSDT-USBX.aml解决ec和供电问题，以及在kernel中使用USBToolBox.kext和UTBMap.kext来定制接口。 据我从各种论坛参考得知以及自己实验，这张型号的主板已经默认屏蔽了EC所以不需要SSDT-EC.aml，并且在Hackintosh下定制的USBPorts.kext可包含定制接口信息，即这一个就可以代替另外两个，而供电信息可以用USBPower.kext可解决，这样相对来说更加简洁高效。 关于为什么不修改ACPI而使用Kernel，因为10.15往后，usb的电源控制就直接放在了io resource，而在10.14中，苹果的usb电源控制是放在ec目录下的，所以写了ec都会写个usbx来帮助苹果具有电池的设备进行快速充电

抱歉回复晚了，感谢你的建议，后续更新时会考虑修改方案。

此外，关于 `据我从各种论坛参考得知以及自己实验，这张型号的主板已经默认屏蔽了EC` 这一点，希望可以给个指路的链接或告知一下实验的具体步骤。

**Comment by 1205129045x** [comment]
大佬，我是msi b450m 主板，我看你很久以前发过这个型号的efi，请问现在给amd cpu做usb映射是不是和给intel cpu做usb映射方法不同，我是看opencore官方文档，用里面的方法定制usb就行了吗？

**Comment by VanXNF** [comment]
> 大佬，我是msi b450m 主板，我看你很久以前发过这个型号的efi，请问现在给amd cpu做usb映射是不是和给intel cpu做usb映射方法不同，我是看opencore官方文档，用里面的方法定制usb就行了吗？

按官方文档说的来就行，没区别的
