### ISSUE TITLE
技嘉主板默认屏蔽ec问题

### ISSUE THREAD

**Issue by Cyanrel** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#33]
https://dortania.github.io/Getting-Started-With-ACPI/Universal/ec-methods/manual.html#edits-to-the-sample-ssdt
文献参考地址，技嘉这张板就是最后一种情况，
另外可不可以留下个联系方式，还有一些问题想要讨论          

  > 抱歉回复晚了，感谢你的建议，后续更新时会考虑修改方案。

此外，关于 `据我从各种论坛参考得知以及自己实验，这张型号的主板已经默认屏蔽了EC` 这一点，希望可以给个指路的链接或告知一下实验的具体步骤。

_Originally posted by @VanXNF in https://github.com/VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro/issues/32#issuecomment-1643866769_

**Comment by VanXNF** [comment]
> https://dortania.github.io/Getting-Started-With-ACPI/Universal/ec-methods/manual.html#edits-to-the-sample-ssdt 文献参考地址，技嘉这张板就是最后一种情况， 另外可不可以留下个联系方式，还有一些问题想要讨论
> 
> > 抱歉回复晚了，感谢你的建议，后续更新时会考虑修改方案。
> 
> 此外，关于 `据我从各种论坛参考得知以及自己实验，这张型号的主板已经默认屏蔽了EC` 这一点，希望可以给个指路的链接或告知一下实验的具体步骤。
> 
> _Originally posted by @VanXNF in [#32 (comment)](https://github.com/VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro/issues/32#issuecomment-1643866769)_

你留一个我来添加你吧

**Comment by Cyanrel** [comment]
这条消息不知道能不能收到，这个邮箱对应的QQ



---原始邮件---
发件人: "Victor ***@***.***&gt;
发送时间: 2023年7月20日(周四) 晚上10:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro] 技嘉主板默认屏蔽ec问题 (Issue #33)




  
https://dortania.github.io/Getting-Started-With-ACPI/Universal/ec-methods/manual.html#edits-to-the-sample-ssdt 文献参考地址，技嘉这张板就是最后一种情况， 另外可不可以留下个联系方式，还有一些问题想要讨论
  
抱歉回复晚了，感谢你的建议，后续更新时会考虑修改方案。
  
此外，关于 据我从各种论坛参考得知以及自己实验，这张型号的主板已经默认屏蔽了EC 这一点，希望可以给个指路的链接或告知一下实验的具体步骤。
 
Originally posted by @VanXNF in #32 (comment)
  
你留一个我来添加你吧

**Comment by VanXNF** [comment]
> 这条消息不知道能不能收到，这个邮箱对应的QQ
> […](#)
> ---原始邮件--- 发件人: "Victor ***@***.***&gt; 发送时间: 2023年7月20日(周四) 晚上10:04 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro] 技嘉主板默认屏蔽ec问题 (Issue #33) https://dortania.github.io/Getting-Started-With-ACPI/Universal/ec-methods/manual.html#edits-to-the-sample-ssdt 文献参考地址，技嘉这张板就是最后一种情况， 另外可不可以留下个联系方式，还有一些问题想要讨论 抱歉回复晚了，感谢你的建议，后续更新时会考虑修改方案。 此外，关于 据我从各种论坛参考得知以及自己实验，这张型号的主板已经默认屏蔽了EC 这一点，希望可以给个指路的链接或告知一下实验的具体步骤。 Originally posted by @VanXNF in #32 (comment) 你留一个我来添加你吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

邮件回复issue时邮箱是隐藏的，你可以发邮件到 vanxnf@gmail.com

**Comment by VanXNF** [comment]
> https://dortania.github.io/Getting-Started-With-ACPI/Universal/ec-methods/manual.html#edits-to-the-sample-ssdt 文献参考地址，技嘉这张板就是最后一种情况， 另外可不可以留下个联系方式，还有一些问题想要讨论
> 
> > 抱歉回复晚了，感谢你的建议，后续更新时会考虑修改方案。
> 
> 此外，关于 `据我从各种论坛参考得知以及自己实验，这张型号的主板已经默认屏蔽了EC` 这一点，希望可以给个指路的链接或告知一下实验的具体步骤。
> 
> _Originally posted by @VanXNF in [#32 (comment)](https://github.com/VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro/issues/32#issuecomment-1643866769)_

我 dump 了 DSDT 看了一下，`H_EC` 有 `_STA` 方法等价于没有 EC 的情况，也就是你说的技嘉默认屏蔽了 EC，但是 macOS 需要的 EC 还是要虚拟一个出来的，也就是这句 `instead we'll need to create a "dummy" EC for macOS`，所以 SSDT-EC 还是需要的。
