### ISSUE TITLE
CFG Lock 解锁这一步有点问题

### ISSUE THREAD

**Issue by slb116763814** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#4]
本主板 F3版本 BIOS 中无 CFG Lock 解锁选项，可在安装前在选择界面中选择 CFG Lock.efi 进行解锁，后可正常安装。
请问这一步操作有详细说明嘛。因为我也是同主板，设置里没有这个解锁，但又不会操作这个安装前解锁的步骤。
谢谢。

**Comment by VanXNF** [comment]
> 本主板 F3版本 BIOS 中无 CFG Lock 解锁选项，可在安装前在选择界面中选择 CFG Lock.efi 进行解锁，后可正常安装。
> 
> 请问这一步操作有详细说明嘛。因为我也是同主板，设置里没有这个解锁，但又不会操作这个安装前解锁的步骤。
> 
> 谢谢。

你看一下我EFI文件下，tools 文件夹里面有一个 CFG 解锁的工具，如果在启动前picker 选单中选中一次 CFG 解锁即可，如果选单中没有则需要在config.plist 里启用一下。

**Comment by VanXNF** [comment]
具体可以参考这个帖子 [CFG解锁](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1866331&highlight=B460M)

**Comment by slb116763814** [comment]
好的，谢谢，但还有一个问题我有必要问一下。
我的配置：
b460 aorus pro主板
i5 10400
核显
DP 1.4 输出
显示器是AOC U27P1U
我的显示器上有两个小喇叭，声音选数码输出的时候显示器没有声音，这个怎么设置？声音肯定是从DP线传过来的，那我选数码输出应该是对的。

**Comment by VanXNF** [comment]
> 好的，谢谢，但还有一个问题我有必要问一下。
> 我的配置：
> b460 aorus pro主板
> i5 10400
> 核显
> DP 1.4 输出
> 显示器是AOC U27P1U
> 我的显示器上有两个小喇叭，声音选数码输出的时候显示器没有声音，这个怎么设置？声音肯定是从DP线传过来的，那我选数码输出应该是对的。选其它几个声音选项也都没有声音。

显示器自带喇叭的话，应该会识别的，在输出选项里会有你显示器名字的一项，需要选择那一项，你可以看一下我的readme文档，最下面的一张图片，最下面一项就是我的显示器，使用dp接口的。不过 mac 系统外接显示器是无法调节音量的，所以需要自己在显示器设置里调节大小。

**Comment by slb116763814** [comment]
我直接用你的EFI，会花屏。是不是需要修改参数改成DP输出？

**Comment by VanXNF** [comment]
> 我直接用你的EFI，会花屏。是不是我需要按照你写的，已知问题第二点，单核显用户建议改为 00009B3E 

我没有对单集显情况做详尽的测试，只更改id也许会有帮助，这个需要你自己进行实验了，或者从其他人处寻求更多帮助。

**Comment by Qingtian239113** [comment]
我的也是直接花屏，单核显
