### ISSUE TITLE
如何生成imac20,1的三碼？？

### ISSUE THREAD

**Issue by s20076001** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#5]
如何生成imac20,1的三碼？？

**Comment by VanXNF** [comment]
> 如何生成imac20,1的三碼？？

在配置文件中我已经预置了一一份 iMac20,1 的三码，如果你不需要登录 apple id 可以不用在意， 如果你需要使用的话，可以在进系统后使用最新的 OpenCore Configurator 生成三码。
