### ISSUE TITLE
intel wifi ax200 disconnected after a few minutes

### ISSUE THREAD

**Issue by nhd2106** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#7]
Hi there, many thanks for your posting.
I have a small issue with wifi.
my intel wifi  ax200 have disconnected after a few minutes.
have you got this issue before?
btw, could you please share your wifi router specs ( is it 5Ghz band?)
thanks in advance.
have a nice day.

**Comment by VanXNF** [comment]
I do not get this issue I think although I use Ethernet mainly. And here is my [pic].(https://tva1.sinaimg.cn/large/007S8ZIlly1gjmsyor5g8j30hu1cs0z8.jpg)

**Comment by nhd2106** [comment]
thanks for your response.
now, im using ethernet too:">
