### ISSUE TITLE
Internet slow with kext AX200

### ISSUE THREAD

**Issue by LongCX** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#8]
Hi pro,

I using kext [Airportitlwm.kext], [IntelBluetoothFirmware.kext] of you for card Intel AX200.
But speed internet very slow. You have solution fix it ?

Same wifi.
Speed on Iphone: **Unit MB/s**
<img src="https://i0.wp.com/s1.uphinh.org/2020/10/18/2020-10-18-11.47.15.jpg" alt="2020-10-18-11.47.15.jpg" border="0" />

Speed on my PC hackintosh: **Unit Mbps/s**
<img src="https://i0.wp.com/s1.uphinh.org/2020/10/18/nh-chp-Man-hinh-2020-10-18-luc-11.52.05.png" alt="nh-chp-Man-hinh-2020-10-18-luc-11.52.05.png" border="0" />

**Comment by VanXNF** [comment]
Enmmm, I think you should open the issue in [itlwm](https://github.com/OpenIntelWireless/itlwm) .
