### ISSUE TITLE
please efi file

### ISSUE THREAD

**Issue by vuminhthanh3010** [VanXNF/Hackintosh-Gigabyte-B460M-Aorus-Pro#9]
Uncle, can I ask if I have Main like yours, but I don't use VGA and wifi card. If you take your EFI home and use it, you will remove any leftovers, please help me with details. thank you uncle

**Comment by VanXNF** [comment]
Read the readme first and this [guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html).
